dependencies:
- torch==2.10.0
- tifffile==2026.4.11
- ipywidgets==8.1.7
- matplotlib==3.10.0
- numpy==2.0.2
- scipy==1.16.3
- zarr==3.2.1
- numcodecs==0.16.5
- scikit-image==0.26.0
- pandas==2.2.2
- networkx==3.6.1
- numba==0.60.0
- cellpose==4.1.1
- simpleitk==2.5.5
- instanseg-torch==0.1.1
- tqdm==4.67.3
description: 'This notebook ''NucleiSky2DApp.ipynb'' is for running NucleiSky2D as
  an App. NucleiSky is a constellation-based registration framework designed to align
  microscopy images by matching the spatial arrangement of cell nuclei. It estimates
  a 2D similarity transform (rotation, uniform scale, and translation) between images,
  robustly handling challenging conditions such as partial overlap, missing nuclei,
  segmentation noise, or differing magnifications. '
linux_dependencies: []
macos_dependencies: []
python_version: 3.12.13
windows_dependencies: []
